name: CI

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - '**'
    tags:
      - 'v*'


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 24.x
        uses: actions/setup-node@v1
        with:
          node-version: 24.x
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
        bun-version: latest

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: |
          npm pkg set scripts.prepare="true"
          bun ci

      - name: Build
        run: bun run build

      - name: Run unit tests
        run: bun run test:unit
        # TODO надо подумать над обходом cloudflare
#      - name: Run e2e tests
#        run: npm run test:e2e

      - name: Run all checks
        run: bun run check

  publish:
    needs:
      - test
    runs-on: ubuntu-latest
    if: contains('
      refs/heads/dev
      refs/heads/master
      ', github.ref) || startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 24.x
        uses: actions/setup-node@v1
        with:
          node-version: 24.x

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
        bun-version: latest

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y rsync

      - name: cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: node_modules-${{ hashFiles('**/package-lock.json')}}

      - name: Extract branch name
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Extract tag name
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        id: extract_tag

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check env
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.extract_tag.outputs.tag }}
          echo ${{ steps.extract_branch.outputs.branch }}


      # Если мастер - деплоим в корень
      - name: Set target folder
        uses: haya14busa/action-cond@v1
        id: target_folder
        if: success()
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags') }}
          if_true: "release"
          if_false: ${{ steps.extract_branch.outputs.branch }}

      - name: Download suffix
        uses: haya14busa/action-cond@v1
        id: server_suffix
        if: success()
        with:
          cond: ${{ startsWith(github.server_url, 'https://gitverse.ru') }}
          if_true: ${{ github.server_url }}/api/repos/${{ github.repository }}/raw/branch/release/${{ steps.target_folder.outputs.value }}/
          if_false: ${{ github.server_url }}/${{ github.repository }}/raw/release/${{ steps.target_folder.outputs.value }}/

      - name: Install dependencies
        run: |
          npm pkg set scripts.prepare="true"
          bun ci

      - name: Build
        run: |
          echo $DOWNLOAD_SUFFIX
          export DOWNLOAD_SUFFIX=$DOWNLOAD_SUFFIX
          bun run build
        env:
          DOWNLOAD_SUFFIX: '${{ steps.server_suffix.outputs.value }}'

      - name: Deploy to release branch
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: release # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: ${{ steps.target_folder.outputs.value }}
