name: Sync from gitverse to github

env:
  DEST_REPO: Apkawa/best_price_userscript
on:
  schedule:
    # Каждый час
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    # Must be run only gitverse
    # On github must be failed
    if: gitverse.repository == env.DEST_REPO
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          # Fetches all history for branches and tags
          fetch-depth: 0

      - name: Mirror push
        run: |
          git fetch -p origin
          git remote add mirror https://${{ secrets.GH_ACCESS_TOKEN }}@github.com/${DEST_REPO}.git
          git push mirror --mirror
